### PR TITLE
#5 fix validation for fixed membership

### PR DESCRIPTION
**Pull request by sunilpawar**
https://github.com/Skvare/com.skvare.membershipextra/issues/5

### CODE REVIEW

**Comment by sunilpawar** [comment]
@freeform-sg can you check this patch work for you ?

**Comment by freeform-sg** [comment]
Thank you - I have tested and it's working for members who are renewing, but I need to do additional testing as I am now getting a new error if it's someone getting a membership for the first time (I still need to confirm if it's unique to my own system or a bug).

**Comment by BPCP** [comment]
I just spent the morning tracking down this same bug but came to a different solution. $startDate in line 137 is being set to the date the current membership starts but then is used as the NEW starting date for calculating $dateNewEdnDate.
The simple solution is to change line 137 to:
$startDate = date('Ymd', strtotime($membershipDetail['fixed_period_start_day'] . ' ' . ($membershipEndYear+1)));
I am not sure of the etiquette of opening competing pull requests but would be happy to do so. (cleaned up a few typos too)

**Comment by sunilpawar** [comment]
@BPCP can you explain your test scenario so that i would be easy to re-create issue at my end...

**Comment by BPCP** [comment]
Sure, A membership that uses a calendar year of Jan 1 through Dec 31 registration opens on the prior dec 1, the grace period is between Jan 1 and June 1st. Anyone trying to renew was given the message (paraphrase) you will not be able to renew until Dec 2021. Even though it is obviously past that date.
I did not test with different scenarios but it seemed obvious by the code that the start date was being set to the start of the current active membership and then being used later as the start date for the new renewed membership. the prior suggested patch seemed to just short circuit the entire scheme.

**Pull request merged**
